### ISSUE TITLE
What would you think about additional functionality from the standard C4 library?

### ISSUE THREAD

**Issue by jtreher** [8T4/c4sharp#19]
One thing I really like on the base Plantuml-stdlib is the ability to add version tags to show systems changing (planned deprecation, future systems). I think we could leverage this right out of the box with some additional configuration options on c4sharp's API but I wasn't sure if you were trying to keep this library super simple or not.

![image](https://user-images.githubusercontent.com/1258179/137128809-841cfd43-b68d-41a4-8352-9561e9f60e23.png)

Or

![image](https://user-images.githubusercontent.com/1258179/137129176-767c5685-1b30-4f5b-8dc7-fe6ebdac242a.png)

**Comment by yanjustino** [comment]
@jtreher wow, dude! You read my mind... I already wrote some code to start this idea some time ago! Fill free to submit a PR to contemplate this feature!

https://github.com/8T4/c4sharp/blob/38d0696c7796dd9e490f4f727538341ddf33f67d/src/components/C4Sharp/Models/Structure.cs#L19

**Comment by yanjustino** [comment]
This issues was implemented. Please, see the [Release 4.1.x](https://github.com/8T4/c4sharp/releases/tag/v4.1.x)! Thank you for your contribution.
