### ISSUE TITLE
Dependencies with vulnerabilities

### ISSUE THREAD

**Issue by visudade** [8T4/c4sharp#36]
Hi c4sharp Team,
I ran a scan with snyk and noticed that there are some vulnerable dependencies being used:
System.Text.Encodings.Web@4.7.0
System.Net.Http@4.3.0
System.Text.RegularExpressions@4.3.0
Is it possible to change the references in src/C4Sharp.Tools/C4Sharp.Tools.csproj to the most up-to-date versions?

**Comment by yanjustino** [comment]
@visudade, Thank you for notify the vulnerabilities issues in C4Sharp. We'll fix it soon as possible!
